// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace CodexLSGameplayTags
{
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_PrimaryAttack);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Dash);

	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_PrimaryAttack);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Dash);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_MeleeAttack);

	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Dashing);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Dead);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Attacking);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Dead);

	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Player_PrimaryAttack);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Player_Dash);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_MeleeAttack);

	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Type_Grunt);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Type_Runner);

	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Health);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_MaxHealth);
	CODEXGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cooldown);
}
