"""Generate and import the original STEP 6 sound set for PROJECT: LAST STAND.

The WAV files are synthesized locally by this script.  No third-party audio or
EditorSounds are used, so the source and license trail stays self-contained.
Run from Unreal Editor Python or UnrealEditor-Cmd -run=PythonScript.
"""

from __future__ import annotations

import json
import math
import random
import struct
import wave
from pathlib import Path

import unreal


SAMPLE_RATE = 44_100
OUTPUT_ROOT = Path(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_saved_dir()))
OUTPUT_ROOT /= "AgentGameTest/Codex/Step06"
WAV_ROOT = OUTPUT_ROOT / "AudioSource"
REPORT_PATH = OUTPUT_ROOT / "AudioBuildReport.json"
LICENSE_NOTE = "Procedurally generated by this repository script; no external source."


def _envelope(index: int, count: int, attack: float, release: float) -> float:
    position = index / max(1, count - 1)
    attack_gain = min(1.0, position / max(attack, 1.0e-4))
    release_gain = min(1.0, (1.0 - position) / max(release, 1.0e-4))
    return max(0.0, min(attack_gain, release_gain))


def _sine(phase: float) -> float:
    return math.sin(phase * math.tau)


def _tone_sweep(t: float, start_hz: float, end_hz: float, duration: float) -> float:
    slope = (end_hz - start_hz) / max(duration, 1.0e-4)
    phase = start_hz * t + 0.5 * slope * t * t
    return _sine(phase)


def _soft_clip(value: float) -> float:
    return math.tanh(value * 1.35) / math.tanh(1.35)


def _render_sound(name: str, duration: float, generator, seed: int) -> Path:
    sample_count = max(1, int(round(duration * SAMPLE_RATE)))
    rng = random.Random(seed)
    samples = []
    peak = 0.0
    for index in range(sample_count):
        t = index / SAMPLE_RATE
        value = _soft_clip(generator(t, index, sample_count, rng))
        samples.append(value)
        peak = max(peak, abs(value))

    normalizer = 0.90 / max(peak, 1.0)
    pcm = bytearray()
    for value in samples:
        pcm.extend(struct.pack("<h", int(max(-1.0, min(1.0, value * normalizer)) * 32767)))

    WAV_ROOT.mkdir(parents=True, exist_ok=True)
    wav_path = WAV_ROOT / f"{name}.wav"
    with wave.open(str(wav_path), "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(SAMPLE_RATE)
        wav_file.writeframes(bytes(pcm))
    return wav_path


def _attack(t, i, n, rng):
    env = _envelope(i, n, 0.015, 0.72) ** 1.6
    laser = 0.72 * _tone_sweep(t, 1_050.0, 180.0, n / SAMPLE_RATE)
    snap = 0.22 * (rng.random() * 2.0 - 1.0) * math.exp(-t * 30.0)
    return env * (laser + snap)


def _dash(t, i, n, rng):
    env = _envelope(i, n, 0.08, 0.44)
    noise = rng.random() * 2.0 - 1.0
    air = noise * (0.38 + 0.30 * _sine(t * 11.0))
    sweep = 0.42 * _tone_sweep(t, 260.0, 680.0, n / SAMPLE_RATE)
    return env * (air + sweep)


def _player_damage(t, i, n, rng):
    env = _envelope(i, n, 0.01, 0.82) ** 1.2
    thud = 0.82 * _tone_sweep(t, 125.0, 48.0, n / SAMPLE_RATE)
    grit = 0.22 * (rng.random() * 2.0 - 1.0) * math.exp(-t * 16.0)
    return env * (thud + grit)


def _enemy_hit(t, i, n, rng):
    env = _envelope(i, n, 0.008, 0.86) ** 2.0
    metal = 0.55 * _sine(t * 520.0) + 0.35 * _sine(t * 1_360.0)
    crack = 0.25 * (rng.random() * 2.0 - 1.0) * math.exp(-t * 36.0)
    return env * (metal + crack)


def _enemy_death(t, i, n, rng):
    env = _envelope(i, n, 0.018, 0.76) ** 1.35
    boom = 0.70 * _tone_sweep(t, 145.0, 38.0, n / SAMPLE_RATE)
    debris = 0.28 * (rng.random() * 2.0 - 1.0) * math.exp(-t * 7.0)
    return env * (boom + debris)


def _note_sequence(t, notes, note_length, decay=8.0):
    index = min(len(notes) - 1, int(t / note_length))
    local_t = t - index * note_length
    return _sine(local_t * notes[index]) * math.exp(-local_t * decay)


def _wave_start(t, i, n, rng):
    env = _envelope(i, n, 0.02, 0.20)
    return env * (0.70 * _note_sequence(t, (330.0, 440.0, 660.0), 0.16, 5.0))


def _wave_clear(t, i, n, rng):
    env = _envelope(i, n, 0.02, 0.22)
    return env * (0.68 * _note_sequence(t, (392.0, 523.25, 659.25), 0.18, 4.2))


def _victory(t, i, n, rng):
    env = _envelope(i, n, 0.015, 0.28)
    melody = _note_sequence(t, (261.63, 329.63, 392.0, 523.25), 0.25, 3.5)
    shimmer = 0.18 * _sine(t * 1_046.5) * math.exp(-t * 1.8)
    return env * (0.72 * melody + shimmer)


def _game_over(t, i, n, rng):
    env = _envelope(i, n, 0.02, 0.30)
    melody = _note_sequence(t, (392.0, 311.13, 233.08, 174.61), 0.24, 2.8)
    return env * (0.70 * melody + 0.16 * _tone_sweep(t, 92.0, 45.0, n / SAMPLE_RATE))


def _ui_confirm(t, i, n, rng):
    env = _envelope(i, n, 0.01, 0.82) ** 2.4
    return env * (0.65 * _sine(t * 880.0) + 0.24 * _sine(t * 1_760.0))


SOUND_SPECS = (
    ("S_Player_Attack_Codex", "/Game/AgentGameTest/Codex/Audio/Player", 0.18, _attack, 6101),
    ("S_Player_Dash_Codex", "/Game/AgentGameTest/Codex/Audio/Player", 0.36, _dash, 6102),
    ("S_Player_Damage_Codex", "/Game/AgentGameTest/Codex/Audio/Player", 0.30, _player_damage, 6103),
    ("S_Enemy_Hit_Codex", "/Game/AgentGameTest/Codex/Audio/Enemy", 0.16, _enemy_hit, 6201),
    ("S_Enemy_Death_Codex", "/Game/AgentGameTest/Codex/Audio/Enemy", 0.62, _enemy_death, 6202),
    ("S_Wave_Start_Codex", "/Game/AgentGameTest/Codex/Audio/Game", 0.58, _wave_start, 6301),
    ("S_Wave_Clear_Codex", "/Game/AgentGameTest/Codex/Audio/Game", 0.70, _wave_clear, 6302),
    ("S_Victory_Codex", "/Game/AgentGameTest/Codex/Audio/Game", 1.18, _victory, 6303),
    ("S_GameOver_Codex", "/Game/AgentGameTest/Codex/Audio/Game", 1.12, _game_over, 6304),
    ("S_UI_Confirm_Codex", "/Game/AgentGameTest/Codex/Audio/UI", 0.10, _ui_confirm, 6401),
)


def _import_sound(wav_path: Path, asset_name: str, destination_path: str):
    task = unreal.AssetImportTask()
    task.filename = str(wav_path)
    task.destination_path = destination_path
    task.destination_name = asset_name
    task.automated = True
    task.replace_existing = True
    task.replace_existing_settings = True
    task.save = True
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])

    object_path = f"{destination_path}/{asset_name}.{asset_name}"
    sound = unreal.load_asset(object_path)
    if sound is None:
        raise RuntimeError(f"Sound import failed: {object_path}")

    sound.set_editor_property("looping", False)
    sound.set_editor_property("volume", 0.78)
    unreal.EditorAssetLibrary.save_loaded_asset(sound, only_if_is_dirty=False)
    return object_path, sound


def main() -> None:
    report = {
        "step": 6,
        "agent": "Codex",
        "source": LICENSE_NOTE,
        "sample_rate": SAMPLE_RATE,
        "channels": 1,
        "bit_depth": 16,
        "sounds": [],
        "success": False,
    }

    for asset_name, destination_path, duration, generator, seed in SOUND_SPECS:
        wav_path = _render_sound(asset_name, duration, generator, seed)
        object_path, sound = _import_sound(wav_path, asset_name, destination_path)
        report["sounds"].append(
            {
                "asset": object_path,
                "wav": str(wav_path),
                "duration_seconds_requested": duration,
                "duration_seconds_imported": round(float(sound.get_editor_property("duration")), 4),
                "license": LICENSE_NOTE,
            }
        )

    report["success"] = True
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    unreal.log(f"CODEX_STEP6_AUDIO_BUILD Success=true Count={len(report['sounds'])} Report={REPORT_PATH}")


if __name__ == "__main__":
    main()
